# Generated by Django 4.2 on 2025-06-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "duration",
                    models.CharField(help_text="e.g. 5 Days / 4 Nights", max_length=50),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_from", models.DateField()),
                ("image", models.ImageField(upload_to="vacation_tours/")),
            ],
        ),
    ]
