# Generated by Django 4.2 on 2025-06-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_vacationtour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacationtour",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vacationtour",
            name="duration",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vacationtour",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="vacation_tours/"),
        ),
        migrations.AlterField(
            model_name="vacationtour",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
