# Generated by Django 4.2 on 2025-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0005_slideimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_group",
                    models.CharField(
                        choices=[("Manager", "Manager"), ("Staff", "Staff")],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
