# Generated by Django 4.2 on 2025-06-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
