# Generated by Django 4.2 on 2025-06-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_contactmessage_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='sent_at',
        ),
    ]
