# Generated by Django 4.2 on 2025-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_rename_created_at_contactmessage_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_from', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/images/')),
            ],
        ),
    ]
